### ISSUE TITLE
Can you add a manpage?

### ISSUE THREAD

**Issue by williamjmorenor** [jsvine/csvcat#1]
Hi

I am trying to package your script in Fedora repo, can you please add a man page to your scritp?

Fedora Packaging Guidelines request than any ejecutable under /usr/bin should have a man page

It could be good if you release a versión of your script so I can use the versión in the package name

Regards

**Comment by jsvine** [comment]
Hi, William. That's a good idea. I'll add a man page and version soon.

**Comment by williamjmorenor** [comment]
Thanks

I have opened the review request for add your script to the Fedora repo

https://bugzilla.redhat.com/show_bug.cgi?id=1177406

**Comment by williamjmorenor** [comment]
Packaged

https://admin.fedoraproject.org/pkgdb/package/csvcat/

**Comment by jsvine** [comment]
Thanks! :+1:
